### ISSUE TITLE
Create a Navbar 🚀 

### ISSUE THREAD

**Issue by pooranjoyb** [pooranjoyb/BeatBridge#1]
## Tasks :

- Use Tailwind CSS to create a customized Glass Navbar 
- Make sure that the Navigation Bar is Responsive with a Hamburger Menu in the Smaller Screens.
- Color of the Navbar should match the current theme

**Comment by rohitroy-github** [comment]
I would like to work on this issue in accordance with Hacktoberfest !

**Comment by pooranjoyb** [comment]
> I would like to work on this issue in accordance with Hacktoberfest !

Go ahead, All the Best!

**Comment by subham-byte** [comment]
I would like to add up to your issue I can do the work with all the requirements.

**Comment by pooranjoyb** [comment]
Update? @rohitroy-github

**Comment by rohitroy-github** [comment]
I'm working on the issue. I'll give you an update soon.

**Comment by pooranjoyb** [comment]
> I would like to add up to your issue I can do the work with all the requirements.

You can start working on this.

**Comment by subham-byte** [comment]
@pooranjoyb  can u please label it under hactoberfest tag?
