### ISSUE TITLE
Update Player UI with the theme 🎨 

### ISSUE THREAD

**Issue by pooranjoyb** [pooranjoyb/BeatBridge#10]
### Task : 

- Make sure that the UI of the player is updated with that of the theme of the webpage
- Use gradients and colors that're used in the `Home.jsx`
- Align the Music Player to the center
- Add the Play button

**Comment by Jalaj028** [comment]
I would like to work on this, can you assign it to me

**Comment by pooranjoyb** [comment]
> I would like to work on this, can you assign it to me

Go for it! :rocket:

**Comment by Jalaj028** [comment]
already created a pr, please let me know if i missed out on something
