### ISSUE TITLE
Build UI for Page 2 🚀 

### ISSUE THREAD

**Issue by pooranjoyb** [pooranjoyb/BeatBridge#12]
### Task : 

- Follow the UI given in [Canva](https://www.canva.com/design/DAFwMI7K-is/ASm25HUugly2IThgiR906g/edit?utm_content=DAFwMI7K-is&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton) below and develop the UI for page 2
- Use `Futura Font Set` for the UI
- `GET STARTED` button should hit the route `/player/`

**Comment by CS50X-RGB** [comment]
@pooranjoyb hi I want to work on this issue

**Comment by pooranjoyb** [comment]
> @pooranjoyb hi I want to work on this issue

Go Ahead @CS50X-RGB 🔥

**Comment by CS50X-RGB** [comment]
Ohhk @pooranjoyb sure can u give some idea about the colors like pink and peach is it? 😅

**Comment by CS50X-RGB** [comment]
okay sure @pooranjoyb

**Comment by CS50X-RGB** [comment]
@pooranjoyb how to get the images used there?

**Comment by pooranjoyb** [comment]
> @pooranjoyb how to get the images used there? can you provide me edit access too it would be helpful for me

@CS50X-RGB 
Opps! Sorry that I missed that out,
Here are the two gradients : `#FF86C8` & `#FBA277`
And about the `img` just add a sample one, I'll co-author commits on your PR and add the original once you open it 👍

**Comment by CS50X-RGB** [comment]
ohh thanks @pooranjoyb
