### ISSUE TITLE
Build UI for Page 3 🚀 

### ISSUE THREAD

**Issue by pooranjoyb** [pooranjoyb/BeatBridge#13]
### Task : 

- Follow the UI given in [Canva](https://www.canva.com/design/DAFwMI7K-is/ASm25HUugly2IThgiR906g/edit?utm_content=DAFwMI7K-is&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton) below and develop the UI for page 3
- Use `Futura Font Set` for the UI
- `github.com/pooranjoyb/BeatBridge` button should open up the **Github Repository** in the new tab.

**Comment by Jalaj028** [comment]
I would like to work on this.
Is there a separate component to be created for page 3 or it should be in continuation with the home.jsx component?

**Comment by pooranjoyb** [comment]
No, all should be separate components. 👍 @Jalaj028

**Comment by pooranjoyb** [comment]
Hey @Jalaj028 what's the update?

**Comment by Jalaj028** [comment]
Hey @pooranjoyb working on it, will create a pr within 2 hours

**Comment by pooranjoyb** [comment]
> Hey @pooranjoyb working on it, will create a pr within 2 hours

No issues, take a deadline till today okay.

**Comment by Jalaj028** [comment]
thanks
