### ISSUE TITLE
Add Table of content in readme.md file

### ISSUE THREAD

**Issue by ayushsarode** [pooranjoyb/BeatBridge#16]

**Comment by pooranjoyb** [comment]
> 

Please describe the issue. @ayushsarode 
How will this issue help our contributors?

**Comment by ayushsarode** [comment]
Since the document is lengthy, I would like to include a table of contents to facilitate convenient access to the content.

**Comment by pooranjoyb** [comment]
> Since the document is lengthy, I would like to include a table of contents to facilitate convenient access to the content.

Ok do it. @ayushsarode

**Comment by pooranjoyb** [comment]
Update? @ayushsarode

**Comment by AshwinSriram11** [comment]
Can I work on this issue @pooranjoyb ?

**Comment by pooranjoyb** [comment]
> Can I work on this issue @pooranjoyb ?
> 

Go for it @AshwinSriram11
