### ISSUE TITLE
[Feature] : Add a sidebar 

### ISSUE THREAD

**Issue by shreyasanap** [pooranjoyb/BeatBridge#18]
- I have created a sidebar for the landing page .
- If this seems fine please assign this issue to me.

![image](https://github.com/pooranjoyb/BeatBridge/assets/121751187/ca8b43c8-6e5b-4cdd-8539-20cb1c49f0a6)

**Comment by pooranjoyb** [comment]
> - I have created a sidebar for the landing page .
> - If this seems fine please assign this issue to me.
> 
> ![image](https://github.com/pooranjoyb/BeatBridge/assets/121751187/ca8b43c8-6e5b-4cdd-8539-20cb1c49f0a6)
> 

Go for it, but please make sure that the sidebar's colors and font should match the theme of the website. Also make sure it's responsive.

**Comment by shreyasanap** [comment]
Sure !
