### ISSUE TITLE
Create a Flask Server 🌐 

### ISSUE THREAD

**Issue by pooranjoyb** [pooranjoyb/BeatBridge#2]
### Task : 
- Create a Flask server in a folder named `backend`
- Initiate Home Route with the React App

**Comment by devsargam** [comment]
@pooranjoyb can you please elaborate more on this?

**Comment by pooranjoyb** [comment]
> @pooranjoyb can you please elaborate more on this?

You'll have to initiate the Backend for the application.

- Create a folder in the Root directory named `backend`
- Create a `server.py` file inside it
- Import and install required dependencies for creating the Flask Server
- Create `/` route for the application.
- Make sure that React App Runs in the Flask Server upon starting it.

Don't forget to add `requirements.txt` file in the `backend` directory.

**Comment by devsargam** [comment]
Got it. @pooranjoyb can you assign it to me?

**Comment by erokemwa** [comment]
Would also like to work on the backend sir

**Comment by H3c7o4** [comment]
Hello devs. I will also like to work on the backend if it possible.
