### ISSUE TITLE
Add Workflow run to checkup linting and formatting

### ISSUE THREAD

**Issue by MannuVilasara** [pooranjoyb/BeatBridge#21]
Please assign me this issue under hactoberfest

Will be adding workflow run to check code formatting which will help other contributors to read the code efficiently

![image](https://github.com/pooranjoyb/BeatBridge/assets/117009138/bb30655a-a6e7-46b9-99f5-6ee76c68e1b9)

![image](https://github.com/pooranjoyb/BeatBridge/assets/117009138/332026ea-7800-419a-bceb-8f86724237ca)

**Comment by pooranjoyb** [comment]
Yes you can do that. Go for it :rocket:
@MannuVilasara
