### ISSUE TITLE
Music Player UI breaks in Full Screen

### ISSUE THREAD

**Issue by pooranjoyb** [pooranjoyb/BeatBridge#24]
### Tasks : 

- Make sure that the UI doesn't break while exiting from the full screen
- There should a smooth transition to the full screen when clicked on the button
- As of now, there's only the background on the full screen, please make some UI changes so that the Player looks fine in the full screen mode.

**Comment by fring-12** [comment]
Hi, @pooranjoyb I want to contribute on this issue . Could you please assign it to me ?

**Comment by pooranjoyb** [comment]
> Hi, @pooranjoyb I want to contribute on this issue . Could you please assign it to me ?

Go for it! @fring-12

**Comment by pooranjoyb** [comment]
Update @fring-12 ?
