### ISSUE TITLE
Add Animations with Framer-Motion 🌟 

### ISSUE THREAD

**Issue by pooranjoyb** [pooranjoyb/BeatBridge#25]
### Tasks : 

- Add animations using `framer-motion` library for `React`
- Use `Sliding animations` for the contents in the `Home Screen`
- Checkout [here](https://www.framer.com/motion/animation/) for reference

**Comment by soykot2910** [comment]
Hi, @pooranjoyb  I want to contribute on this issue . Could you please assign it to me ?

**Comment by pooranjoyb** [comment]
> Hi, @pooranjoyb  I want to contribute on this issue . Could you please assign it to me ?

Go Ahead! All the best 👍 @soykot2910

**Comment by soykot2910** [comment]
@pooranjoyb I have added Framer Motion animations to the home page. Could you please review it? [ PR](https://github.com/pooranjoyb/BeatBridge/pull/28)
