### ISSUE TITLE
Create a Footer 🚀 

### ISSUE THREAD

**Issue by pooranjoyb** [pooranjoyb/BeatBridge#27]
### Task : 

- Make sure that you create a new `Footer Component`
- Add it both in the `Home Page` as well as in the `Player Page`

**Comment by Princeton21** [comment]
I'd like to work on this

**Comment by Princeton21** [comment]
do you have any particular requirements in the footer?

**Comment by pooranjoyb** [comment]
No, as of now I just want a simple & minimalistic footer that matches the theme :)
You can add : 
- Github Icon, that redirects to github.
- Copyright ©️ BeatBridge should be added.
- It's height should match the Navbar height.

**Comment by pooranjoyb** [comment]
Update @Princeton21 ?

**Comment by Princeton21** [comment]
Ya I was busy at college . I'll raise the PR tonight.

**Comment by AshwinSriram11** [comment]
Can I work on this issue? @pooranjoyb

**Comment by pooranjoyb** [comment]
Go for it! 🚀 @AshwinSriram11

**Comment by veerendra19codes** [comment]
Hey @pooranjoyb ,i can work on this issue, just tell me how many columns and what all data you want to display in footer section, i can raise  a PR within 24hrs🙌✌️Please Assign me!🥳

**Comment by pooranjoyb** [comment]
> Hey @pooranjoyb ,i can work on this issue, just tell me how many columns and what all data you want to display in footer section, i can raise  a PR within 24hrs🙌✌️Please Assign me!🥳

Go for it!

**Comment by veerendra19codes** [comment]
attempting!

**Comment by veerendra19codes** [comment]
hey @pooranjoyb ,actually someone has already created a small footer as shown in the screenshot , but i think they forgot to create a PR . I can add more contents to this footer and make it darker ,do you have any content/data you want to add in footer ?

**Screenshot**
![smallfooter](https://github.com/pooranjoyb/BeatBridge/assets/113845853/9adb6c04-6450-47fd-9523-7622f4511e15)
