### ISSUE TITLE
Initiate Spotify API with Music Player 🎵 

### ISSUE THREAD

**Issue by pooranjoyb** [pooranjoyb/BeatBridge#29]
### Tasks : 
- Create an `.env` file in the root directory to store the secrets for `Spotify API`
- Use `Node-Fetch` or `Axios` to hit the API and fetch songs in the Applicaiton
- `console.log()` the song data received from the Spotify API in the `Developer Console`
- Don't forget to add a `Search icon` below the search text field, to hit the API.

#### NOTE : We'll integrate it with the music player in the coming issues.

**Comment by AshwinSriram11** [comment]
@pooranjoyb Can I work on this issue?

**Comment by pooranjoyb** [comment]
> @pooranjoyb Can I work on this issue?
> 

Go for it!

**Comment by pooranjoyb** [comment]
Update? @AshwinSriram11

**Comment by AshwinSriram11** [comment]
@pooranjoyb I have created a PR kindly check it.
