### ISSUE TITLE
Landing Page for Beat Bridge 🚀 

### ISSUE THREAD

**Issue by pooranjoyb** [pooranjoyb/BeatBridge#3]
## Task :

- Design a Landing Page for the Application
- Use Light Gradients Colors
- Make sure the Navbar created in #1 is added there.
- Check for Responsiveness

**Comment by lokesh-wagh** [comment]
hey can you give me a figma design for the page or some design's to follow

**Comment by pooranjoyb** [comment]
> hey can you give me a figma design for the page or some design's to follow

Here's the link Follow this
https://www.canva.com/design/DAFwMI7K-is/ASm25HUugly2IThgiR906g/edit?utm_content=DAFwMI7K-is&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

**Comment by subham-byte** [comment]
I would like to contribute to your project. Can u assign it to me under hacktoberfest tag

**Comment by lokesh-wagh** [comment]
where can i find the resource's for making 
like image asset's and other thing's
also how do you want the navbar to be??

**Comment by lokesh-wagh** [comment]
Assign me this issue I think i can make this

**Comment by pooranjoyb** [comment]
> where can i find the resource's for making like image asset's and other thing's also how do you want the navbar to be??

The Navbar should be a off Canvas Navbar and it should match the theme of the website.
And about the resource please check the `public` directory. I've already added the background image there.
@lokesh-wagh

**Comment by pooranjoyb** [comment]
> I would like to contribute to your project. Can u assign it to me under hacktoberfest tag

Hello @subham-byte Would be glad to assign a issue to you, but this issue is already assigned. would be glad if you'd look into other issues or create one. :)

**Comment by pooranjoyb** [comment]
> I would like to contribute to your project. Can u assign it to me under hacktoberfest tag

Update? @lokesh-wagh

**Comment by lokesh-wagh** [comment]
Hey @pooranjoyb 
I actually have my mid sense right now 
You can unassign me 
I will work on this later if it's open

**Comment by lokesh-wagh** [comment]
Sry for inconvenience

**Comment by AshwinSriram11** [comment]
Can I work on this issue @pooranjoyb ?

**Comment by pooranjoyb** [comment]
Assigned @subham-byte & @AshwinSriram11

**Comment by AshwinSriram11** [comment]
@pooranjoyb I have created a PR. Kindly please review it.
