### ISSUE TITLE
Make navbar stick at the top while scrolling

### ISSUE THREAD

**Issue by veerendra19codes** [pooranjoyb/BeatBridge#43]
Make the navbar stick at the top like most of the websites .It will allow users to use navbar while scrolling for better UI and user experience. I can fix this,Please assign me!!🥳✌️

**Comment by pooranjoyb** [comment]
> Make the navbar stick at the top like most of the websites .It will allow users to use navbar while scrolling for better UI and user experience. I can fix this,Please assign me!!🥳✌️

You can start working, I'll assign you.

**Comment by veerendra19codes** [comment]
Ok🥳✌️

**Comment by Ayusht777** [comment]
@pooranjoyb  does this website has live link

**Comment by pooranjoyb** [comment]
> @pooranjoyb  does this website has live link
> 

Well, we're planning to deploy once initial build is complete.

**Comment by anand-harsh** [comment]
Hi @pooranjoyb , Can you please assign me this issue
