### ISSUE TITLE
Create the Python Script in `server.py` that serves the static `vite build`

### ISSUE THREAD

**Issue by pooranjoyb** [pooranjoyb/BeatBridge#46]
### Task : 

- [ ] Modify the script in `package.json` and set path of `build` directory to server.
- [ ] Use those static files and serve them within the server.

**Comment by yash8000** [comment]
please assign me this

**Comment by pooranjoyb** [comment]
GO for it! @yash8000

**Comment by pooranjoyb** [comment]
What's the update @yash8000 ?
Are you upto it?

**Comment by yash8000** [comment]
yes
