### ISSUE TITLE
Redesign the UI for the Player

### ISSUE THREAD

**Issue by pooranjoyb** [pooranjoyb/BeatBridge#47]
### Tasks : 

- As the UI of the player seems quite broken, a new UI for the same is suggested.
- You can first drop the canva design for the same here, it can be redesigned accordingly.
- A better option will be to update the existing code.

Please drop your thoughts and take up the issue.

**Comment by Nupoor10** [comment]
Hello, Can I work on this?? Will try to send the canva design in few days and update code according to the feedback on the same

**Comment by pooranjoyb** [comment]
Go for it! @Nupoor10 🚀

**Comment by Nupoor10** [comment]
Hello, I have completed the Canva design for this. The first page is the desktop view and the second is the mobile view. Would love your feedback on the same!

https://www.canva.com/design/DAF3A37UOVc/fkguGyhFuMBfq0lrQwDwKA/edit?utm_content=DAF3A37UOVc&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

**Comment by pooranjoyb** [comment]
Awesome, Go for it! :)) 🚀 @Nupoor10
