### ISSUE TITLE
Create Routes for the Application ⭐ 

### ISSUE THREAD

**Issue by pooranjoyb** [pooranjoyb/BeatBridge#5]
## Task : 

- Use `react-router-dom` to create routes like the `/` home route, `/player` for music player route.
- Make sure that the `/` home route renders the Landing Page i.e, `Home.jsx` and not any other component.
- Make your changes in the `main.jsx` file

[Click here](https://github.com/pooranjoyb/gdscsmit_website/blob/9cabfe5168151bd5abbee51294579b8566642449/src/main.jsx#L8)  for reference

**Comment by vaishsabu** [comment]
can you assign this issue to me?

**Comment by pooranjoyb** [comment]
> can you assign this issue to me?

Go ahead! 🚀
