### ISSUE TITLE
Feat: Top Artists page with artists sample cards

### ISSUE THREAD

**Issue by AaadityaG** [pooranjoyb/BeatBridge#55]
Please Allow me to work on it for KWoC

**Comment by pooranjoyb** [comment]
Go for it! :))) @AaadityaG

**Comment by pooranjoyb** [comment]
Just an update for you. Please make sure the card UI design remains consistent throughout the application (you can check the deployment for reference).

### So your task will be : 
- To create a route for `Top Artists`  called `/artists` that can be navigated through `Navbar`
- Use `Spotify-API` fetch the `Top-Artists` data
- Add the `fetchTopArtist()` function in the `API_Controller.js` class for ease.

@AaadityaG

**Comment by AaadityaG** [comment]
Ok

**Comment by AaadityaG** [comment]
> Just an update for you. Please make sure the card UI design remains consistent throughout the application (you can check the deployment for reference).
> 
> ### So your task will be :
> * To create a route for `Top Artists`  called `/artists` that can be navigated through `Navbar`
> * Use `Spotify-API` fetch the `Top-Artists` data
> * Add the `fetchTopArtist()` function in the `API_Controller.js` class for ease.
> 
> @AaadityaG

Bro i tried but wasn't able to fetch data, but I have some dummy cards(responsive) also it took my lot of time... 

Let me know if you want me to raise a pr with this! 

![Beat Bridge — Mozilla Firefox 07-01-2024 05_28_22 PM](https://github.com/pooranjoyb/BeatBridge/assets/114663382/72eac2ad-ffc3-4f47-9b57-594a2229187e)

**Comment by AaadityaG** [comment]
Yes
