### ISSUE TITLE
fix : contributors.md

### ISSUE THREAD

**Issue by rohitroy-github** [pooranjoyb/BeatBridge#7]
I think there's an issue with the file because it shows to clone git clone https://github.com/your-username/Music-Player-RecEngine.git | I don't know which repository it is because the current repository is [BeatBridge](https://github.com/pooranjoyb/BeatBridge)

What's the actual thing here, please check ?

**Comment by pooranjoyb** [comment]
Yup that's a typo
Fix it :)
